name: Node.js CI

on:
  push:
    branches: [main] # Replace 'main' with the name of your default branch if different
  pull_request:
    branches: [main] # Replace 'main' with the name of your default branch if different

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # You can specify multiple Node.js versions here

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
